CREATE DATABASE IF NOT EXISTS lessonplanner;
USE lessonplanner;

CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Responses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    response TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE USER IF NOT EXISTS 'REDACTED'@'localhost' IDENTIFIED WITH mysql_native_password BY 'REDACTED';

GRANT ALL PRIVILEGES ON lessonplanner.* TO 'REDACTED'@'localhost';

FLUSH PRIVILEGES;